name: Deploy Admin

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Admin via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e

            cd /root/D-Zessert-admin

            npm install
            npm run build

            pm2 restart dzessert-admin || PORT=3000 pm2 start npm --name dzessert-admin -- start
            pm2 save
